[package]
name = "mini-codex-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "mini-codex"
path = "src/main.rs"

[dependencies]
mini-codex-app-server = { path = "../app-server" }
anyhow.workspace = true
mini-codex-arg0 = { path = "../arg0" }
mini-codex-core = { path = "../core" }
mini-codex-protocol = { path = "../protocol" }
tokio.workspace = true

