export const functionCalling = {
  zh: {
    overview: "模型不会直接执行工具。它先生成工具名和参数，harness 执行真实操作，再把结果送回模型继续推理。",
    introTitle: "一切能力皆基于 LLM API 请求",
    intro: [
      "程序和模型的交互都基于 LLM API 请求。要让模型知道它可以使用哪些外部能力，请求体中就需要携带工具定义，也就是 tools 字段。",
    ],
    rustTitle: "用 Rust 发送带 tools 的请求",
    rustIntro: "运行这段代码，通过 Responses API 向 DeepSeek 发送真实请求，并查看模型返回的 function_call 输出项。",
    rustEmpty: "运行后在这里查看编译结果，以及模型生成的工具名和调用参数。",
    toolDefinitionIntro: "请求中的 tools 定义如下：",
    toolDefinitionLabel: "请求参数 · tools",
    toolFields: [
      { field: "tools", text: "工具定义数组；一次请求可以声明多个可用工具。" },
      { field: "type", text: "工具类型。function 表示这是一个可由模型请求调用的函数工具，也是最常见的，也有别的标准类型，比如custom,web，都看response协议的定义支持哪些类型，单度有个web类型的原因是因为codex官方支持线上web调用" },
      { field: "name", text: "告诉LLM我这个工具名" },
      { field: "description", text: "告诉LLM工具用途说明，帮助模型判断何时应该调用它。" },
      { field: "parameters", text: "告诉LLM，你调用这个工具，需要哪些入餐" },
      { field: "parameters.type", text: "object 表示调用参数整体是一个 JSON 对象。LLM要是调用就会按照返回一个对象" },
      { field: "properties", text: "参数对象允许包含的字段，以及每个字段的类型和说明。" },
      { field: "location", text: "本例的城市参数；type: string 要求它是字符串，description 解释字段语义。" },
      { field: "required", text: "必填字段列表；这里表示调用这个工具必须提供 location 参数" },
    ],
    toolDefinitionSummary: "这段 tools 定义是在告诉 AI：程序为你提供了一个名为 get_weather 的函数工具，它可以查询指定城市的当前气温；如果决定调用它，需要传入一个字符串类型的 location 参数。",
    responsePrintIntro: "print 打印结果如下：",
    callItemIntro: "重点看 output 字段中的这个对象：",
    callItemLabel: "重点摘录 · function_call",
    callItemSummary: "这里模型返回了一个 function_call，表示它要调用 get_weather 工具；arguments 中的 location 是杭州，也就是想查看杭州的天气。call_id是我们之后要回传的，标识这次函数调用，因为可能会有很多个工具调用，所以需要一个唯一标识来区分，模型也能根据call_id知道后面的传递的结果是哪次工具调用的结果",
    toolResultIntro: "工具执行完成后，结果最终要回传给 LLM，模型才能根据结果继续回答。Responses 协议也规定了回传格式",
    toolResultLabel: "回传工具结果 · function_call_output",
    toolResultSummary: "这里的 output 是将天气结果序列化后的 JSON 字符串；它也可以是普通文本。harness 将这个对象追加到 history，再通过下一次请求的 input 字段把包含原调用和工具结果的历史传给模型。模型便能通过相同的 call_id，把这份结果与前面的 get_weather 调用对应起来。",
    responseExplanation: "由此可以看出，我们在http的请求参数中告诉模型，我们提供哪些tools，每个tools的描述和调用参数，模型决定调用哪个工具之后，就会返回调用json，之后我在harness中解析这个json，并执行工具，之后吧并将工具执行结果传递给Ai，让Ai进行下一步回答",
    dispatchExampleTitle: "实现真正闭环，工具执行后，将结果传递给Ai，让Ai进行下一步回答，这个也就是大家熟悉的ReAct模式",
    dispatchExampleIntro: "输入 DeepSeek API Key 后运行真实闭环：代码请求模型，在 while 循环中识别 function_call、执行本地 get_weather、回传同 call_id 的 function_call_output，再次请求模型直到得到最终回答。",
    dispatchExampleEmpty: "运行后在这里查看每轮模型关键输出、工具结果和最终回答。",
    executionTitle: "总结",
    executionIntro: [
      "模型只负责生成调用意图：工具名、arguments 和 call_id。真正解析参数、检查权限、执行代码和收集结果的是 我们自己写的 harness。模型本身不会运行 get_weather，也不会直接接触终端或文件系统。",
      "工具执行完成后，harness 把结果包装成 function_call_output，并使用同一个 call_id 与原调用配对。这个结果进入会话历史，随后再次请求模型；模型可能给出最终回答，也可能继续调用其他工具。",
    ],
    flowLabel: "一次工具调用的完整闭环",
    flowSteps: [
      { title: "发送上下文", detail: "harness 将用户输入和 tools 定义发送给模型。" },
      { title: "收到调用", detail: "模型返回 function_call：name、arguments、call_id。" },
      { title: "执行", detail: "harness 根据模型返回的function_call，找到对应的工具，并执行" },
      { title: "继续采样", detail: "结果进入 history，模型知道结果后继续推理" },
    ],
    callLabel: "模型真实响应 · reasoning + function_call",
    reference: "参考：OpenAI Function Calling 指南",
    back: "回顾上一章：Responses / Chat · 模型协议",
    next: "下一章：Codex Function Calling · 源码解析",
  },
  en: {
    overview: "The model does not execute tools directly. It emits a tool name and arguments; the harness performs the action and returns the result for the model to continue reasoning.",
    introTitle: "Every capability starts with an LLM API request",
    intro: [
      "Every model capability in an agent starts with an LLM API request. To tell the model which external capabilities it may use, the request body includes a tools field.",
      "The tools field does not contain execution results. It describes each tool's name, purpose, and parameter schema. The request below declares get_weather with one required string parameter, location. The model can then produce a matching tool call in its response.",
    ],
    rustTitle: "Send a tools request with Rust",
    rustIntro: "Run this code against DeepSeek's Responses API and inspect the function_call output item returned by the model. The code only declares the tool; it does not execute a weather lookup inside the sandbox.",
    rustEmpty: "Run the code to see compiler output and the tool name and arguments generated by the model.",
    toolDefinitionIntro: "The request declares its tools as follows:",
    toolDefinitionLabel: "Request parameter · tools",
    toolFields: [
      { field: "tools", text: "An array of tool definitions; one request may advertise multiple tools." },
      { field: "type", text: "The tool kind. function marks a function tool that the model may request." },
      { field: "name", text: "The unique tool name used by function_call to select what should run." },
      { field: "description", text: "Explains what the tool does so the model can decide when to call it." },
      { field: "parameters", text: "A JSON Schema describing the shape of arguments." },
      { field: "parameters.type", text: "object means the complete argument value is a JSON object." },
      { field: "properties", text: "Defines the allowed argument fields together with their types and descriptions." },
      { field: "location", text: "The city argument in this example; type: string requires text, while description explains its meaning." },
      { field: "required", text: "Lists mandatory fields; here every call must provide location." },
    ],
    toolDefinitionSummary: "This tools definition tells the AI that the program provides a function named get_weather for checking the current temperature in a specified city. If the model chooses to call it, it must provide location as a string.",
    responsePrintIntro: "The print output is shown below:",
    callItemIntro: "Focus on this object in the output field:",
    callItemLabel: "Focus item · function_call",
    callItemSummary: "Here the model returns a function_call requesting the get_weather tool. The location in arguments is Hangzhou, so the model wants to look up Hangzhou's weather.",
    toolResultIntro: "After execution, the tool result must be sent back to the LLM so it can continue answering. The Responses protocol defines this return format: the harness creates a function_call_output item, preserves the call_id from the model's call, and puts the result in output. The example below is a tool-result item, not a complete HTTP request. Its weather data is illustrative.",
    toolResultLabel: "Return the tool result · function_call_output",
    toolResultSummary: "Here output is a JSON-encoded string containing the weather result; plain text is also allowed. The harness appends this item to history and sends the history, including the original call and its result, in the next request's input field. The matching call_id links this result to the earlier get_weather call.",
    responseExplanation: "Focus on the function_call object in the output array. The request uses tools to tell the model which tools are available. When the model decides to use one, it returns an item whose type is function_call: name identifies the tool, arguments contains the generated call parameters, and call_id correlates the result. The host recognizes this type, parses and validates arguments, then routes execution to the local function registered under name.",
    dispatchExampleTitle: "Implement a true loop, pass the result to the AI to let the AI continue the next answer",
    dispatchExampleIntro: "Enter a DeepSeek API key to run the real loop. The code requests the model, handles function_call inside a while loop, executes local get_weather, returns function_call_output with the same call_id, and requests the model again until it answers. The weather function uses fixed teaching data; the model request and handoff are real.",
    dispatchExampleEmpty: "Run the code to inspect each model step, the tool result, and the final answer.",
    executionTitle: "Who executes a tool after the model requests it?",
    executionIntro: [
      "The model only produces intent: a tool name, arguments, and a call_id. The Codex harness parses and validates the arguments, applies policy, runs code, and collects the result. The model itself never runs get_weather or directly accesses the terminal or filesystem.",
      "After execution, the harness wraps the result in function_call_output with the same call_id. That item enters conversation history before the model is sampled again; the model may answer or request more tools.",
    ],
    flowLabel: "The complete tool-call loop",
    flowSteps: [
      { title: "Send context", detail: "The harness sends user input and tool definitions to the model." },
      { title: "Receive a call", detail: "The model returns function_call with name, arguments, and call_id." },
      { title: "Build the call", detail: "Codex converts the protocol item into ToolCall and records the request." },
      { title: "Route and run", detail: "ToolRouter selects a registered handler; execution tools also cross approval and sandbox boundaries." },
      { title: "Record output", detail: "The handler output becomes function_call_output with the same call_id." },
      { title: "Sample again", detail: "The output enters history; the next model call answers or requests another tool." },
    ],
    callLabel: "Actual model response · reasoning + function_call",
    reference: "Reference: OpenAI Function Calling guide",
    back: "Review the previous chapter: Responses / Chat Protocols",
    next: "Next: Codex Function Calling · Source Walkthrough",
  },
} as const;

const weatherCallId = "call_00_ZzDcV4aJVgqoLRgV8RmV0142";
const weatherArguments = '{"location": "杭州"}';

export const weatherToolsDefinition = JSON.stringify({
  tools: [{
    type: "function",
    name: "get_weather",
    description: "查询指定城市的当前气温",
    parameters: {
      type: "object",
      properties: {
        location: {
          type: "string",
          description: "城市名称",
        },
      },
      required: ["location"],
    },
  }],
});

export const functionCallResponse = JSON.stringify({
  background: false,
  completed_at: 1790603571,
  content_filters: null,
  created_at: 1790603571,
  error: null,
  frequency_penalty: 0,
  id: "b8a762ff-5c5a-45d7-9103-6259978a251c",
  incomplete_details: null,
  instructions: null,
  max_output_tokens: 256,
  max_tool_calls: null,
  metadata: {},
  model: "deepseek-flash",
  moderation: null,
  object: "response",
  output: [
    {
      content: [
        {
          text: "用户询问杭州当前气温，我应该调用 get_weather 工具。",
          type: "reasoning_text",
        },
      ],
      encrypted_content: "b8a762ff-5c5a-45d7-9103-6259978a251c-0",
      id: "e4079344-a6ed-49e1-8ec5-adbfd93eb0a0",
      status: "completed",
      summary: [],
      type: "reasoning",
    },
    {
      arguments: weatherArguments,
      call_id: weatherCallId,
      id: "6e04178f-54d6-4192-bf73-872a9d8e7c72",
      name: "get_weather",
      status: "completed",
      type: "function_call",
    },
  ],
  parallel_tool_calls: true,
  presence_penalty: 0,
  previous_response_id: null,
  prompt_cache_key: null,
  prompt_cache_retention: null,
  reasoning: {
    effort: null,
    summary: null,
  },
  safety_identifier: null,
  service_tier: "default",
  status: "completed",
  store: false,
  temperature: 1,
  text: {
    format: {
      type: "text",
    },
    verbosity: null,
  },
  tool_choice: "auto",
  tools: [
    {
      description: "查询指定城市的当前气温",
      name: "get_weather",
      parameters: {
        properties: {
          location: {
            description: "城市名称",
            type: "string",
          },
        },
        required: ["location"],
        type: "object",
      },
      strict: null,
      type: "function",
    },
  ],
  top_logprobs: 0,
  top_p: 1,
  truncation: "disabled",
  usage: {
    input_tokens: 300,
    input_tokens_details: {
      cached_tokens: 128,
    },
    output_tokens: 56,
    output_tokens_details: {
      reasoning_tokens: 17,
    },
    total_tokens: 356,
  },
  user: null,
});

export const functionCallItem = JSON.stringify({
  arguments: weatherArguments,
  call_id: weatherCallId,
  id: "6e04178f-54d6-4192-bf73-872a9d8e7c72",
  name: "get_weather",
  status: "completed",
  type: "function_call",
});

export const functionCallResult = JSON.stringify({
  type: "function_call_output",
  call_id: weatherCallId,
  output: JSON.stringify({ location: "杭州", temperature_c: 24, condition: "晴" }),
});

export const toolDispatchRustExample = `use serde_json::{json, Value};
use std::time::Duration;

const MAX_ROUNDS: usize = 3;

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = reqwest::Client::builder()
        .timeout(Duration::from_secs(25))
        .build()?;
    let tools = json!([{
        "type": "function",
        "name": "get_weather",
        "description": "查询指定城市的当前气温",
        "parameters": {
            "type": "object",
            "properties": {
                "location": { "type": "string", "description": "城市名称" }
            },
            "required": ["location"]
        }
    }]);
    let mut history = vec![json!({
        "role": "user",
        "content": "杭州现在多少度？"
    })];
    let mut round = 0;

    while round < MAX_ROUNDS {
        round += 1;
        let response = request_model(&client, &history, &tools).await?;
        let output = response["output"].as_array().cloned().unwrap_or_default();
        print_key_output(round, &output)?;

        let calls: Vec<Value> = output.iter()
            .filter(|item| item["type"].as_str() == Some("function_call"))
            .cloned()
            .collect();
        if calls.is_empty() {
            return Ok(());
        }
        if round == MAX_ROUNDS {
            return Err(std::io::Error::other("达到最大模型轮数").into());
        }

        // DeepSeek Responses API 是无状态的：下一轮必须带回上一轮完整 output。
        history.extend(output.iter().cloned());
        for call in calls {
            let name = required_string(&call, "name")?;
            let arguments = required_string(&call, "arguments")?;
            let call_id = required_string(&call, "call_id")?;
            let result = execute_tool(name, arguments)?;
            println!("工具结果: {}", result);

            history.push(json!({
                "type": "function_call_output",
                "call_id": call_id,
                "output": result.to_string()
            }));
        }
    }
    Ok(())
}

async fn request_model(
    client: &reqwest::Client,
    history: &[Value],
    tools: &Value,
) -> Result<Value, Box<dyn std::error::Error>> {
    let response = client
        .post("https://api.deepseek.com/responses")
        .bearer_auth(std::env::var("DEEPSEEK_API_KEY")?)
        .json(&json!({
            "model": "deepseek-flash",
            "input": history,
            "tools": tools,
            "tool_choice": "auto",
            "stream": false,
            "max_output_tokens": 256
        }))
        .send().await?;
    let status = response.status();
    let body = response.text().await?;
    if !status.is_success() {
        let detail = if body.trim().is_empty() {
            "空响应（通常表示沙箱代理或上游网关失败）"
        } else {
            body.trim()
        };
        return Err(std::io::Error::other(format!(
            "模型请求失败：HTTP {status}；响应：{detail}"
        )).into());
    }
    Ok(serde_json::from_str(&body)?)
}

fn execute_tool(name: &str, arguments: &str) -> Result<Value, Box<dyn std::error::Error>> {
    let arguments: Value = serde_json::from_str(arguments)?;
    match name {
        "get_weather" => Ok(get_weather(required_string(&arguments, "location")?)),
        _ => Err(std::io::Error::other(format!("未注册的工具：{name}")).into()),
    }
}

fn print_key_output(round: usize, output: &[Value]) -> Result<(), serde_json::Error> {
    let key_items: Vec<&Value> = output.iter()
        .filter(|item| matches!(item["type"].as_str(), Some("function_call" | "message")))
        .collect();
    println!("第 {round} 轮模型关键输出:\n{}", serde_json::to_string_pretty(&key_items)?);
    Ok(())
}

fn required_string<'a>(value: &'a Value, field: &str) -> Result<&'a str, std::io::Error> {
    value[field].as_str().ok_or_else(|| {
        std::io::Error::other(format!("缺少字符串字段：{field}"))
    })
}

fn get_weather(location: &str) -> Value {
     // 工具执行使用固定教学数据,大家知道工具是本地执行的就OK
    json!({ "location": location, "temperature_c": 24, "condition": "晴" })
}`;


export const functionCallingRustExample = `use serde_json::{json, Value};

#[tokio::main(flavor = "current_thread")]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let body = json!({
        "model": "deepseek-flash",
        "input": "杭州现在多少度？",
        "tools": [{
            "type": "function",
            "name": "get_weather",
            "description": "查询指定城市的当前气温",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "城市名称"
                    },
                },
                "required": ["location"]
            }
        }],
        "tool_choice": "auto",
        "stream": false,
        "max_output_tokens": 256
    });

    let response: Value = reqwest::Client::new()
        .post("https://api.deepseek.com/responses")
        .bearer_auth(std::env::var("DEEPSEEK_API_KEY")?)
        .json(&body)
        .send().await?
        .error_for_status()?
        .json().await?;

    println!("{}", serde_json::to_string_pretty(&response)?);
    Ok(())
}`;
